#!/bin/bash

cd ~

ln -s .dotfiles/.vimrc
ln -s .dotfiles/.vim
touch .vimrc.local

ln -s .dotfiles/.tmux.conf

mkdir -p .config/fish
ln -s .config/fish .fish
ln -s .dotfiles/.fish/functions .fish
ln -s .dotfiles/.fish/config.fish .fish

ln -s .dotfiles/.bashrc
touch ~/.bashrc.local
